version: "3.9"
services:
  phys-website:
    env_file: ./.env
    command: /bin/sh -c "while sleep 1000; do :; done"
    build:
      context: ./
      args:
        USER_NAME: ${PHYS_USER_NAME}
        USER_EMAIL: ${PHYS_USER_EMAIL}
        SIGNATURE: ${PHYS_USER_SIGNATURE}
        G_MAP_KEY: ${PHYS_USER_GOOGLE_MAP_KEY}
